### ISSUE TITLE
:robot::bug: Github action --- Should the actions fail if the format check fails?

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs4XX-EvolutionaryComputation#151]
### Related Issues or PRs

Noted in #150 
Tested in #149 

### What

The github actions will pass if the formatter was not run on the code. 

### Why

Mystery. Maybe it's just that the code will be formatted anyways, so it does not matter if it fails?

```python
html_theme_options = {
    'logo_only': False,
    'display_version': False,
    'sticky_navigation': True,
}
```

Though, this was still there on the repo and the formatter should have changed the single quotes (`'`) to double quotes (`"`)

### Additional Notes

Noting to be addressed later.

**Comment by jameshughes89** [comment]
I did a quick look at the action and I see this:

```yml
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        SETUPTOOLS_ENABLE_FEATURES="legacy-editable" python -m pip install --editable .
    - name: Verify Format
      run: |
        validate
    - name: Unit Test Sample Code
      run: |
        python -m unittest
```

Which includes
```yml
    - name: Verify Format
      run: |
        validate
```

So it should validate things anyways.
